### ISSUE TITLE
Error: brew install gnuradio --with-brewed-python

### ISSUE THREAD

**Issue by ekimgit** [metacollin/homebrew-gnuradio#26]
since a build with system python does not lead to a running gnuradio-companion, I would like to try a brew python version .... 

$ brew install gnuradio --with-brewed-python
Error: undefined method `deponds_on' for Formulary::Formulae::Gnuradio:Class
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Taps/metacollin/homebrew-gnuradio/gnuradio.rb:48:in `<class:Gnuradio>'
/usr/local/Library/Taps/metacollin/homebrew-gnuradio/gnuradio.rb:3:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:92:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:92:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:82:in `klass'
/usr/local/Library/Homebrew/formulary.rb:71:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:200:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:41:in `install'
/usr/local/Library/brew.rb:135:in `<main>'

**Comment by ekimgit** [comment]
ok, found the typo in line 48 ...

**Comment by vielmetti** [comment]
There are a couple of pull requests that include this patch.

**Comment by metacollin** [comment]
Sorry everyone.  Real life things made me neglect this tap for something like 2 months :(.  I've updated the documentation and totally reworked the formula, please update your taps and give it another try.
